const secrets = require('./secrets.js');

const githubOptions = {
  url: 'https://api.github.com/rate_limit',
  headers: {
    Accept:
      'application/vnd.github.the-key-preview+json,application/vnd.github.v3+json,application/vnd.github.cerberus-preview,application/vnd.github.mockingbird-preview,application/vnd.github.squirrel-girl-preview,application/vnd.github.barred-rock-preview,application/vnd.github.damage-preview,application/vnd.github.ant-man-preview+json,application/vnd.github.cryptographer-preview,application/vnd.github.polaris-preview',
    Authorization: 'token ' + secrets.githubToken,
    'User-Agent': 'jMuzsik'
  }
};

const repos = [
  { language: 'JS', repo: 'freeCodeCamp/freeCodeCamp' },
  { language: 'CSS, JS', repo: 'twbs/bootstrap' },
  { language: 'JS', repo: 'facebook/react' },
  { language: 'Resource', repo: 'EbookFoundation/free-programming-books' },
  { language: 'JS', repo: 'vuejs/vue' },
  { language: 'C++', repo: 'tensorflow/tensorflow' },
  { language: 'JS', repo: 'd3/d3' },
  { language: 'JS', repo: 'airbnb/javascript' },
  { language: 'Resource', repo: 'getify/You-Dont-Know-JS' },
  { language: 'JS', repo: 'facebook/react-native' },
  { language: 'Resource', repo: 'sindresorhus/awesome' },
  { language: 'Resource', repo: 'github/gitignore' },
  { language: 'Shell', repo: 'robbyrussell/oh-my-zsh' },
  { language: 'JS', repo: 'angular/angular.js' },
  { language: 'CSS', repo: 'FortAwesome/Font-Awesome' },
  { language: 'TS', repo: 'Microsoft/vscode' },
  { language: 'JS', repo: 'facebook/create-react-app' },
  { language: 'C++', repo: 'electron/electron' },
  { language: 'C', repo: 'torvalds/linux' },
  { language: 'JS', repo: 'jquery/jquery' },
  { language: 'Resource', repo: 'jwasham/coding-interview-university' },
  { language: 'JS', repo: 'nodejs/node' },
  { language: 'Go', repo: 'moby/moby' },
  { language: 'JS', repo: 'atom/atom' },
  { language: 'CSS', repo: 'daneden/animate.css' },
  { language: 'JS', repo: 'golang/go' },
  { language: 'C++', repo: 'apple/swift' },
  { language: 'JS', repo: 'h5bp/html5-boilerplate' },
  { language: 'JS', repo: 'Semantic-Org/Semantic-UI' },
  { language: 'PHP', repo: 'laravel/laravel' },
  { language: 'JS', repo: 'socketio/socket.io' },
  { language: 'JS', repo: 'meteor/meteor' },
  { language: 'Ruby', repo: 'rails/rails' },
  { language: 'JS', repo: 'reactjs/redux' },
  { language: 'Resource', repo: 'vinta/awesome-python' },
  { language: 'JS', repo: 'expressjs/express' },
  { language: 'JS', repo: 'webpack/webpack' },
  { language: 'JS', repo: 'hakimel/reveal.js' },
  { language: 'Resource', repo: 'nodejs/node-v0.x-archive' },
  { language: 'JS', repo: 'moment/moment' },
  { language: 'CSS', repo: 'google/material-design-icons' },
  { language: 'JS', repo: 'chartjs/Chart.js' },
  { language: 'JS', repo: 'mrdoob/three.js' },
  { language: 'TS', repo: 'Microsoft/TypeScript' },
  { language: 'Java', repo: 'ReactiveX/RxJava' },
  { language: 'Go', repo: 'kubernetes/kubernetes' },
  { language: 'TS', repo: 'ionic-team/ionic' },
  { language: 'Python', repo: 'pallets/flask' },
  { language: 'Ruby', repo: 'jekyll/jekyll' },
  { language: 'JS', repo: 'nwjs/nw.js' },
  { language: 'JS', repo: 'impress/impress.js' },
  { language: 'JS', repo: 'angular/angular' },
  {
    language: 'Resource',
    repo: 'h5bp/Front-end-Developer-Interview-Questions'
  },
  { language: 'Go', repo: 'getlantern/lantern' },
  { language: 'Python', repo: 'jakubroztocil/httpie' },
  { language: 'Python', repo: 'django/django' },
  { language: 'Resource', repo: 'vuejs/awesome-vue' },
  { language: 'JS', repo: 'resume/resume.github.com' },
  { language: 'Resource', repo: 'jlevy/the-art-of-command-line' },
  { language: 'JS', repo: 'typicode/json-server' },
  { language: 'Resource', repo: 'justjavac/free-programming-books-zh_CN' },
  { language: 'Resource', repo: 'CyC2018/Interview-Notebook' },
  { language: 'Obj-C', repo: 'AFNetworking/AFNetworking' },
  { language: 'Python', repo: 'nvbn/thefuck' },
  { language: 'HTML', repo: 'google/material-design-lite' },
  { language: 'TS, JS, CSS', repo: 'ant-design/ant-design' },
  { language: 'Resource', repo: 'NARKOZ/hacker-scripts' },
  { language: 'Python', repo: 'rg3/youtube-dl' },
  { language: 'Java', repo: 'elastic/elasticsearch' },
  { language: 'JS', repo: 'adobe/brackets' },
  { language: 'JS, CSS', repo: 'Dogfalo/materialize' },
  { language: 'Ruby', repo: 'Homebrew/legacy-homebrew' },
  { language: 'JS', repo: 'mui-org/material-ui' },
  { language: 'Python', repo: 'ansible/ansible' },
  { language: 'Resource', repo: 'tensorflow/models' },
  { language: 'JS, Vue', repo: 'ElemeFE/element' },
  { language: 'JS, HTML', repo: 'apache/incubator-echarts' },
  { language: 'CSS', repo: 'necolas/normalize.css' },
  { language: 'C++, Java, Obj-C', repo: 'google/protobuf' },
  { language: 'JS, HTML, PHP', repo: 'blueimp/jQuery-File-Upload' },
  { language: 'Python', repo: 'requests/requests' },
  { language: 'JS', repo: 'gulpjs/gulp' },
  { language: 'Resource', repo: 'toddmotto/public-apis' },
  { language: 'JS', repo: 'yarnpkg/yarn' },
  { language: 'HTML, CSS, JS', repo: 'zurb/foundation-sites' },
  { language: 'Java', repo: 'square/retrofit' },
  { language: 'JS', repo: 'jashkenas/backbone' },
  { language: 'JS', repo: 'GoogleChrome/puppeteer' },
  { language: 'Rust', repo: 'rust-lang/rust' },
  { language: 'JS', repo: 'axios/axios' },
  { language: 'JS', repo: 'lodash/lodash' },
  { language: 'Resource', repo: 'kamranahmedse/developer-roadmap' },
  { language: 'VIM Script, C, Lua', repo: 'neovim/neovim' },
  { language: 'JS', repo: 'babel/babel' },
  { language: 'Resource', repo: 'josephmisiti/awesome-machine-learning' },
  { language: 'Java', repo: 'square/okhttp' },
  { language: 'Resource', repo: 'wasabeef/awesome-android-ui' },
  { language: 'JS', repo: 'google/guava' },
  { language: 'Java', repo: 'Alamofire/Alamofire' },
  { language: 'Swift', repo: 'googlesamples/android-architecture`' },
  { language: 'C, Tcl', repo: 'antirez/redis' },
  { language: 'Assembly', repo: 'chrislgarry/Apollo-11' },
  { language: 'JS', repo: 'ReactTraining/react-router' },
  { language: 'Resource', repo: 'papers-we-love/papers-we-love' },
  { language: 'Resource', repo: 'Trinea/android-open-project' },
  { language: 'JS', repo: 'facebook/immutable-js' },
  { language: 'JS', repo: 'TryGhost/Ghost' },
  { language: 'Resource', repo: 'open-source-society/computer-science' },
  { language: 'Java', repo: 'iluwatar/java-design-patterns' },
  { language: 'C, Python, JS, HTML, Shell', repo: 'firehol/netdata' },
  { language: 'Kotlin, Java', repo: 'JetBrains/kotlin' },
  { language: 'JS, CoffeeScript, HTML', repo: 'nylas/nylas-mail' },
  { language: 'Resource', repo: 'shadowsocks/shadowsocks' },
  { language: 'Resource, Go', repo: 'avelino/awesome-go' },
  { language: 'Resource, Angular', repo: 'johnpapa/angular-styleguide' },
  { language: 'HTML', repo: 'ariya/phantomjs' },
  { language: 'Resource, Github', repo: 'tiimgreen/github-cheat-sheet' },
  { language: 'Java', repo: 'spring-projects/spring-boot' },
  { language: 'Java', repo: 'PhilJay/MPAndroidChart' },
  { language: 'Ruby, JS', repo: 'discourse/discourse' },
  { language: 'Resource', repo: 'dypsilon/frontend-dev-bookmarks' },
  { language: 'Python', repo: 'scrapy/scrapy' },
  { language: 'JS', repo: 'caolan/async' },
  { language: 'JS', repo: 'Modernizr/Modernizr' },
  { language: 'JS', repo: 'adam-p/markdown-here' },
  { language: 'JS, HTML', repo: 'tastejs/todomvc' },
  { language: 'JS', repo: 'serverless/serverless' },
  { language: 'Python', repo: 'minimaxir/big-list-of-naughty-strings' },
  { language: 'Resource, JS', repo: 'lukehoban/es6features' },
  { language: 'Recource, IOS', repo: 'vsouza/awesome-ios' },
  { language: 'JS', repo: 'jashkenas/underscore' },
  { language: 'Shell', repo: 'creationix/nvm' },
  { language: 'Resource, React', repo: 'enaqx/awesome-react' },
  { language: 'JS', repo: 'select2/select2' },
  { language: 'HTML, CoffeeScript', repo: 'harvesthq/chosen' },
  { language: 'JS', repo: 'mozilla/pdf.js' },
  { language: 'JS', repo: 'scikit-learn/scikit-learn' },
  { language: 'JS, Shell', repo: 'Unitech/pm2' },
  { language: 'CSS, HTML, JS', repo: 'sahat/hackathon-starter' },
  { language: 'Go', repo: 'gogs/gogs' },
  { language: 'Resource', repo: 'prakhar1989/awesome-courses' },
  { language: 'Resource', repo: 'karan/Projects' },
  { language: 'JS', repo: 'alvarotrigo/fullPage.js' },
  { language: 'Ruby, JS', repo: 'gitlabhq/gitlabhq' },
  { language: 'Resource', repo: 'caesar0301/awesome-public-datasets' },
  { language: 'JS', repo: 'spring-projects/spring-framework' },
  { language: 'C++', repo: 'BVLC/caffe' },
  { language: 'JS', repo: 'lord/slate' },
  { language: 'C++, Python', repo: 'rethinkdb/rethinkdb' },
  { language: 'JS', repo: 'request/request' },
  { language: 'JS', repo: 'koajs/koa' },
  {
    language: 'Resource',
    repo: 'sdmg15/Best-websites-a-programmer-should-visit'
  },
  { language: 'Resource', repo: 'bayandin/awesome-awesomeness' },
  { language: 'Resource, HTML', repo: 'joshbuchea/HEAD' },
  { language: 'Python', repo: 'certbot/certbot' },
  { language: 'JS, Python', repo: 'apache/incubator-superset' },
  { language: 'Go', repo: 'gohugoio/hugo' },
  { language: 'Java, Kotlin', repo: 'airbnb/lottie-android' },
  { language: 'Resource, Java', repo: 'codepath/android_guides' },
  { language: 'JS, CSS', repo: 'kenwheeler/slick' },
  { language: 'JS, HTML', repo: 'Leaflet/Leaflet' },
  { language: 'Python', repo: 'keras-team/keras' },
  { language: 'Java', repo: 'apache/incubator-dubbo' },
  {
    language: 'Resource, System Design',
    repo: 'donnemartin/system-design-primer'
  },
  { language: 'Resource, Mac', repo: 'jaywcjlove/awesome-mac' },
  { language: 'Obj-C++, Obj-C, C++', repo: 'facebook/pop' },
  { language: 'Resource, Interview', repo: 'alex/what-happens-when' },
  { language: 'CSS', repo: 'jgthms/bulma' },
  { language: 'C, Shell, Perl', repo: 'git/git' },
  { language: 'JS', repo: 'zenorocha/clipboard.js' },
  { language: 'C#', repo: 'shadowsocks/shadowsocks-windows' },
  { language: 'JS, TS', repo: 'emberjs/ember.js' },
  { language: 'Java', repo: 'square/leakcanary' },
  { language: 'JS', repo: 'zeit/hyper' },
  { language: 'Resource, JS, Node', repo: 'sindresorhus/awesome-nodejs' },
  { language: 'CSS, JS', repo: 'FezVrasta/bootstrap-material-design' },
  { language: 'HTML, CSS, JS', repo: 'almasaeed2010/AdminLTE' },
  { language: 'Obj-C', repo: 'rs/SDWebImage' },
  { language: 'JS', repo: 'github/fetch' },
  { language: 'JS', repo: 'facebook/jest' },
  { language: 'HTML, JS', repo: 'Polymer/polymer' },
  { language: 'HTML, CSS, JS', repo: 'google/web-starter-kit' },
  { language: 'Shell', repo: 'nvie/gitflow' },
  { language: 'JS, MakeFile, Ruby', repo: 'Kickball/awesome-selfhosted' },
  { language: 'JS', repo: 'hexojs/hexo' },
  { language: 'C++', repo: 'opencv/opencv' },
  { language: 'Java', repo: 'JakeWharton/butterknife' },
  { language: 'Ruby, CoffeeScript', repo: 'freeCodeCamp/devdocs' },
  { language: 'Ruby, Swift', repo: 'fastlane/fastlane' },
  {
    language: 'Resource, Design Patterns',
    repo: 'kamranahmedse/design-patterns-for-humans'
  },
  {
    language: 'Resource, Go',
    repo: 'astaxie/build-web-application-with-golang'
  },
  { language: 'Swift', repo: 'ReactiveCocoa/ReactiveCocoa' },
  { language: 'Resource, AWS', repo: 'open-guides/og-aws' },
  { language: 'JS', repo: 'balderdashy/sails' },
  { language: 'Java', repo: 'bumptech/glide' },
  { language: 'Ruby', repo: 'plataformatec/devise' },
  { language: 'Resource', repo: 'FreeCodeCampChina/freecodecamp.cn' },
  { language: 'JS', repo: 'Hack-with-Github/awesome-Hacking' },
  { language: 'JS', repo: 'postcss/postcss' },
  { language: 'Scala, Java, Python', repo: 'apache/spark' },
  { language: 'JS', repo: 'videojs/video.js' },
  { language: 'TS', repo: 'grafana/grafana' },
  {
    language: 'Resource, Shell',
    repo: 'herrbischoff/awesome-osx-command-line'
  },
  { language: 'HTML, CSS, JS', repo: 'pure-css/pure' },
  { language: 'Shell, VIM Script', repo: 'mathiasbynens/dotfiles' },
  { language: 'CSS', repo: 'IanLunn/Hover' },
  { language: 'Go', repo: 'syncthing/syncthing' },
  {
    language: 'Resource, Swift',
    repo: 'numbbbbb/the-swift-programming-language-in-chinese'
  },
  { language: 'Python, C', repo: 'python/cpython' },
  { language: 'Ruby', repo: 'hashicorp/vagrant' },
  { language: 'Java, JS, Obj-C, C++', repo: 'apache/incubator-weex' },
  { language: 'Ruby, HTML', repo: 'huginn/huginn' },
  {
    language: 'Resource, Security',
    repo: 'FallibleInc/security-guide-for-developers'
  },
  { language: 'OCaml, JS', repo: 'facebook/flow' },
  { language: 'Go', repo: 'coreos/etcd' },
  { language: 'JS', repo: 'hammerjs/hammer.js' },
  { language: 'JS', repo: 'zeit/next.js' },
  { language: 'Clojure, HTML, CSS, Shell', repo: 'tonsky/FiraCode' },
  { language: 'PHP', repo: 'symfony/symfony' },
  { language: 'TS', repo: 'railsware/upterm' },
  { language: 'TS, CSS, JS, HTML', repo: 't4t5/sweetalert' },
  { language: 'Resource, PHP', repo: 'ziadoz/awesome-php' },
  { language: 'JS', repo: 'bevacqua/dragula' },
  { language: 'Java', repo: 'ReactiveX/RxAndroid' },
  { language: 'Python', repo: 'XX-net/XX-Net' },
  { language: 'JS, Python', repo: 'aosabook/500lines' },
  { language: 'Resource', repo: 'ripienaar/free-for-dev' },
  { language: 'C++, Python, C', repo: 'bitcoin/bitcoin' },
  { language: 'Obj-C', repo: 'BradLarson/GPUImage' },
  {
    language: 'Resource, AI',
    repo: 'ZuzooVn/machine-learning-for-software-engineers'
  },
  { language: 'JS', repo: 'GitbookIO/gitbook' },
  { language: 'JS', repo: 'photonstorm/phaser' },
  { language: 'Obj-C', repo: 'SnapKit/Masonry' },
  { language: 'JS', repo: 'angular/material' },
  {
    language: 'Resource, Interview',
    repo: 'MaximAbramchuck/awesome-interview-questions'
  },
  {
    language: 'Resource, OS',
    repo: 'SamyPesse/How-to-Make-a-Computer-Operating-System'
  },
  { language: 'Resource, JS', repo: 'verekia/js-stack-from-scratch' },
  { language: 'JS', repo: 'npm/cli' },
  { language: 'Java', repo: 'greenrobot/EventBus' },
  { language: 'Resource, SysAdmin', repo: 'kahun/awesome-sysadmin' },
  { language: 'C, PHP', repo: 'php/php-src' },
  { language: 'HTML, JS, CSS', repo: 'usablica/intro.js' },
  { language: 'Java', repo: 'google/iosched' },
  { language: 'Vim Script', repo: 'VundleVim/Vundle.vim' },
  { language: 'CSS, HTML', repo: 'Tencent/weui' },
  { language: 'Swift, Obj-C', repo: 'danielgindi/Charts' },
  { language: 'Rascal', repo: 'racaljk/hosts' },
  { language: 'JS', repo: 'ajaxorg/ace' },
  { language: 'JS', repo: 'pixijs/pixi.js' },
  { language: 'Java', repo: 'nostra13/Android-Universal-Image-Loader' },
  { language: 'TS', repo: 'angular/angular-cli' },
  { language: 'Resource, JS', repo: 'ryanmcdermott/clean-code-javascript' },
  { language: 'C++, PHP, OCaml, Hack', repo: 'facebook/hhvm' },
  { language: 'Swift', repo: 'SwiftyJSON/SwiftyJSON' },
  { language: 'JS', repo: 'petkaantonov/bluebird' },
  { language: 'JS', repo: 'facebook/flux' },
  { language: 'JS', repo: 'bower/bower' },
  { language: 'JS', repo: 'kriasoft/react-starter-kit' },
  { language: 'JS', repo: 'defunkt/jquery-pjax' },
  { language: 'HTML, JS', repo: 'ftlabs/fastclick' },
  { language: 'Resource', repo: 'google/styleguide' },
  { language: 'JS', repo: 'react-boilerplate/react-boilerplate' },
  { language: 'JS', repo: 'zxing/zxing' },
  {
    language: 'Resource, Tensor Flow',
    repo: 'aymericdamien/TensorFlow-Examples'
  },
  { language: 'C, Obj-C, Java, Shell', repo: 'Bilibili/ijkplayer' },
  { language: 'JS', repo: 'pugjs/pug' },
  { language: 'Python, Shell', repo: '0xAX/linux-insides' },
  { language: 'Java', repo: 'square/picasso' },
  { language: 'JS, CSS', repo: 'less/less.js' },
  { language: 'PHP', repo: 'bcit-ci/CodeIgniter' },
  { language: 'JS', repo: 'Automattic/mongoose' },
  { language: 'JS', repo: 'segmentio/nightmare' },
  { language: 'JS', repo: 'dimsemenov/PhotoSwipe' },
  { language: 'Resource, C++', repo: 'isocpp/CppCoreGuidelines' },
  { language: 'JS', repo: 'parse-community/parse-server' },
  { language: 'JS', repo: 'quilljs/quill' },
  { language: 'Resource, Android', repo: 'futurice/android-best-practices' },
  { language: 'JS, CSS', repo: 'postcss/autoprefixer' },
  { language: 'Java', repo: 'facebook/fresco' },
  { language: 'CSS', repo: 'dhg/Skeleton' },
  { language: 'Resource, React-Native', repo: 'jondot/awesome-react-native' },
  { language: 'Python', repo: 'Valloric/YouCompleteMe' },
  { language: 'Java', repo: 'alibaba/fastjson' },
  { language: 'Resource, C++, Python, Deep Learning', repo: 'Microsoft/CNTK' },
  { language: 'JS', repo: 'prettier/prettier' },
  { language: 'Python', repo: 'soimort/you-get' },
  { language: 'Lua', repo: 'jcjohnson/neural-style' },
  { language: 'Java', repo: 'Netflix/Hystrix' },
  { language: 'JS', repo: 'webtorrent/webtorrent' },
  { language: 'JS, HTML', repo: 'juliangarnier/anime' },
  { language: 'CSS, JS', repo: 'twbs/ratchet' },
  { language: 'C++', repo: 'google/leveldb' },
  { language: 'Python', repo: 'tornadoweb/tornado' },
  { language: 'Resource, IOS', repo: 'dkhamsing/open-source-ios-apps' },
  { language: 'CoffeeScript', repo: 'jashkenas/coffeescript' },
  { language: 'Shell, Python', repo: 'dokku/dokku' },
  { language: 'JS', repo: 'vuejs/vuex' },
  { language: 'C++, Python, Perl', repo: 'apache/incubator-mxnet' },
  { language: 'TS', repo: 'ReactiveX/rxjs' },
  {
    language: 'Resource, Interview',
    repo: 'raywenderlich/swift-algorithm-club'
  },
  { language: 'Swift', repo: 'ReactiveX/RxSwift' },
  { language: 'Go', repo: 'ethereum/go-ethereum' },
  { language: 'JS, Yacc', repo: 'knsv/mermaid' },
  { language: 'Ruby, C', repo: 'ruby/ruby' },
  { language: 'Resource, Java', repo: 'akullpp/awesome-java' },
  { language: 'Python', repo: 'wangshub/wechat_jump_game' },
  { language: 'JS', repo: 'markedjs/marked' },
  { language: 'Go', repo: 'mholt/caddy' },
  { language: 'JS', repo: 'RocketChat/Rocket.Chat' },
  { language: 'TS', repo: 'angular-ui/ui-router' },
  { language: 'Python', repo: 'getsentry/sentry' },
  { language: 'CSS', repo: 'tobiasahlin/SpinKit' },
  { language: 'JS', repo: 'developit/preact' },
  { language: 'Obj-C', repo: 'jdg/MBProgressHUD' },
  { language: 'Resource', repo: 'justjavac/awesome-wechat-weapp' },
  { language: 'JS', repo: 'kriskowal/q' },
  { language: 'JS, HTML', repo: 'storybooks/storybook' },
  { language: 'JS', repo: 'nolimits4web/Swiper' },
  { language: 'JS, TS', repo: 'julianshapiro/velocity' },
  { language: 'C#', repo: 'dotnet/corefx' },
  {
    language: 'Resource, Deep Learning',
    repo: 'songrotek/Deep-Learning-Papers-Reading-Roadmap'
  },
  { language: 'C', repo: 'wg/wrk' },
  { language: 'JS, CSS', repo: 'designmodo/Flat-UI' },
  { language: 'JS', repo: 'cheeriojs/cheerio' },
  { language: 'CSS', repo: 'HubSpot/pace' },
  { language: 'Resource, JS', repo: 'standard/standard' },
  { language: 'JS', repo: 'mochajs/mocha' },
  { language: 'JS', repo: 'facebook/draft-js' },
  {
    language: 'Resource, Design Patterns, PHP',
    repo: 'domnikl/DesignPatternsPHP'
  },
  { language: 'JS', repo: 'jlmakes/scrollreveal' },
  { language: 'C, Perl', repo: 'ggreer/the_silver_searcher' },
  { language: 'JS', repo: 'hubotio/hubot' },
  { language: 'Resource, C++', repo: 'fffaraz/awesome-cpp' },
  { language: 'C++, JS', repo: 'mongodb/mongo' },
  { language: 'Java', repo: 'google/gson' },
  { language: 'TS', repo: 'angular/material2' },
  { language: 'Resource, JS', repo: 'rwaldron/idiomatic.js' },
  { language: 'JS', repo: 'airbnb/enzyme' },
  { language: 'Go', repo: 'hashicorp/terraform' },
  { language: 'Go', repo: 'hashicorp/consul' },
  { language: 'Resource, Blog', repo: 'fouber/blog' },
  { language: 'Rust', repo: 'google/xi-editor' },
  { language: 'HTML, JS, C++', repo: 'facebookresearch/fastText' },
  {
    language: 'Resource, Math',
    repo:
      'CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers'
  },
  { language: 'HTML, JS', repo: 'madrobby/zepto' },
  { language: 'Obj-C', repo: 'airbnb/lottie-ios' },
  { language: 'Resource, Ruby', repo: 'bbatsov/ruby-style-guide' },
  { language: 'JS', repo: 'gatsbyjs/gatsby' },
  { language: 'Java', repo: 'Blankj/AndroidUtilCode' },
  { language: 'C, C++', repo: 'kripken/emscripten' },
  { language: 'JS', repo: 'enyo/dropzone' },
  { language: 'JS', repo: 'jasmine/jasmine' },
  { language: 'Resource, Swift', repo: 'matteocrippa/awesome-swift' },
  { language: 'Emacs Lisp', repo: 'syl20bnr/spacemacs' },
  { language: 'C++', repo: 'tesseract-ocr/tesseract' },
  { language: 'HTML, JS', repo: 'codemirror/CodeMirror' },
  { language: 'Ruby, CSS', repo: 'twbs/bootstrap-sass' },
  { language: 'JS', repo: 'etsy/statsd' },
  { language: 'Go, Gherkin, Shell', repo: 'github/hub' },
  { language: 'C++', repo: 'facebook/osquery' },
  { language: 'Java', repo: 'alibaba/druid' },
  { language: 'Resource', repo: 'zeeshanu/learn-regex' },
  { language: 'Resource, Python', repo: 'faif/python-patterns' },
  { language: 'JS', repo: 'GoogleChrome/lighthouse' },
  { language: 'Resource', repo: 'interagent/http-api-design' },
  { language: 'Resource, Git', repo: 'k88hudson/git-flight-rules' },
  { language: 'Kotlin, C', repo: 'shadowsocks/shadowsocks-android' },
  { language: 'Elixir, Erlang', repo: 'elixir-lang/elixir' },
  { language: 'JS', repo: 'wycats/handlebars.js' },
  { language: 'HTML', repo: 'ionic-team/ionicons' },
  { language: 'Resource, Programming', repo: 'braydie/HowToBeAProgrammer' },
  { language: 'Java, C++, C', repo: 'libgdx/libgdx' },
  { language: 'JS', repo: 'riot/riot' },
  { language: 'JS', repo: 'facebook/prepack' },
  { language: 'C, Vim Script', repo: 'vim/vim' },
  { language: 'HTML, CSS, JS', repo: 'puikinsh/gentelella' },
  { language: 'JS', repo: 'visionmedia/superagent' },
  { language: 'HTML, CSS', repo: 'desandro/masonry' },
  { language: 'Resource, Swift', repo: 'ipader/SwiftGuide' },
  { language: 'Python', repo: 'facebookresearch/Detectron' },
  { language: 'Resource, Python', repo: 'kennethreitz/python-guide' },
  { language: 'JS', repo: 'naptha/tesseract.js' },
  { language: 'Go', repo: 'astaxie/beego' },
  { language: 'JS', repo: 'FormidableLabs/webpack-dashboard' },
  { language: 'Swift', repo: 'PerfectlySoft/Perfect' },
  { language: 'TS', repo: 'DefinitelyTyped/DefinitelyTyped' },
  { language: 'Resource, Electron', repo: 'sindresorhus/awesome-electron' },
  { language: 'JS', repo: 'nefe/You-Dont-Need-jQuery' },
  { language: 'Resource', repo: 'MostlyAdequate/mostly-adequate-guide' },
  { language: 'Resource, JS', repo: 'sorrycc/awesome-javascript' },
  { language: 'Python, Shell', repo: 'chubin/cheat.sh' },
  { language: 'Swift', repo: 'SnapKit/SnapKit' },
  { language: 'Resource, Blog', repo: 'kilimchoi/engineering-blogs' },
  { language: 'Kotlin, Java', repo: 'google/flexbox-layout' },
  { language: 'JS', repo: 'remy/nodemon' },
  { language: 'Python', repo: 'docker/compose' },
  { language: 'Python', repo: 'ipython/ipython' },
  { language: 'Obj-C', repo: 'ccgus/fmdb' },
  { language: 'Obj-C, Swift', repo: 'realm/realm-cocoa' },
  {
    language: 'Resource, Security',
    repo: 'drduh/macOS-Security-and-Privacy-Guide'
  },
  { language: 'Lua, Perl', repo: 'kong/kong' },
  { language: 'JS', repo: 'jiahaog/nativefier' },
  { language: 'JS', repo: 'gruntjs/grunt' },
  {
    language: 'Resource, Depp Learning',
    repo: 'terryum/awesome-deep-learning-papers'
  },
  { language: 'JS', repo: 'node-inspector/node-inspector' },
  { language: 'Go', repo: 'gin-gonic/gin' },
  { language: 'PHP', repo: 'fzaninotto/Faker' },
  { language: 'Vim Script, HTML, Perl, Shell', repo: 'altercation/solarized' },
  { language: 'Resource', repo: 'julycoding/The-Art-Of-Programming-By-July' },
  { language: 'PHP', repo: 'yiisoft/yii2' },
  { language: 'Ruby', repo: 'homebrew/homebrew-cask' },
  { language: 'JS', repo: 'jaredhanson/passport' },
  { language: 'Go', repo: 'prometheus/prometheus' },
  { language: 'Vue, JS, CSS', repo: 'ElemeFE/mint-ui' },
  { language: 'Go', repo: 'influxdata/influxdb' },
  { language: 'Resource, Interviews', repo: 'kdn251/interviews' },
  { language: 'Obj-C, C++', repo: 'textmate/textmate' },
  { language: 'Ruby, JS', repo: 'diaspora/diaspora' },
  { language: 'Python, Shell, BatchFile', repo: 'adobe-fonts/source-code-pro' },
  { language: 'C++, PowerShell, BatchFile', repo: 'cmderdev/cmder' },
  { language: 'JS, HTML', repo: 'requirejs/requirejs' },
  { language: 'Obj-C', repo: 'ibireme/YYKit' },
  { language: 'JS', repo: 'VincentGarreau/particles.js' },
  { language: 'JS', repo: 'browserify/browserify' },
  { language: 'C++', repo: 'google/guetzli' },
  { language: 'Resource, JS', repo: 'bolshchikov/js-must-watch' },
  { language: 'Scala, Shell', repo: 'apache/predictionio' },
  { language: 'Vue, JS', repo: 'bailicangdu/vue2-elm' },
  { language: 'JS', repo: 'Marak/faker.js' },
  { language: 'JS, HTML, CSS', repo: 'wekan/wekan' },
  { language: 'JS', repo: 'avajs/ava' },
  { language: 'JS', repo: 'reduxjs/react-redux' },
  { language: 'JS', repo: 'vuejs/vue-cli' },
  { language: 'Swift', repo: 'MengTo/Spring' },
  { language: 'C++', repo: 'grpc/grpc' },
  { language: 'Java', repo: 'chrisbanes/PhotoView' },
  { language: 'Go, JS', repo: 'inconshreveable/ngrok' },
  {
    language: 'Resource, Deep Learning, Chinese',
    repo: 'exacity/deeplearningbook-chinese'
  },
  { language: 'Java', repo: 'netty/netty' },
  { language: 'JS, HTML', repo: 'RubaXa/Sortable' },
  { language: 'Kotlin', repo: 'Kotlin/anko' },
  { language: 'JS', repo: 'janl/mustache.js' },
  { language: 'JS', repo: 'facebook/relay' },
  { language: 'JS', repo: 'airbnb/react-sketchapp' },
  { language: 'Ruby', repo: 'Homebrew/brew' },
  { language: 'Ruby', repo: 'sass/sass' },
  { language: 'JS', repo: 'infernojs/inferno' },
  { language: 'JS', repo: 'sequelize/sequelize' },
  { language: 'Resource, JS, React', repo: 'ruanyf/react-demos' },
  { language: 'JS', repo: 'yabwe/medium-editor' },
  { language: 'Java', repo: 'afollestad/material-dialogs' },
  { language: 'TS', repo: 'NativeScript/NativeScript' },
  { language: 'Swift', repo: 'vapor/vapor' },
  { language: 'Go', repo: 'cockroachdb/cockroach' },
  { language: 'Resource, Git', repo: 'git-tips/tips' },
  { language: 'Go', repo: 'mattermost/mattermost-server' },
  { language: 'JS', repo: 'Flipboard/react-canvas' },
  { language: 'JS, TS', repo: 'mobxjs/mobx' },
  {
    language: 'Resource, Interviewing',
    repo: 'donnemartin/interactive-coding-challenges'
  },
  { language: 'Shell, HTML, Python', repo: 'StreisandEffect/streisand' },
  { language: 'Go', repo: 'drone/drone' },
  {
    language: 'CSS, Vim Script, Emacs Lisp, JS',
    repo: 'chriskempson/tomorrow-theme'
  },
  { language: 'HTML', repo: 'google/fonts' },
  { language: 'Resource, Docker', repo: 'wsargent/docker-cheat-sheet' },
  { language: 'C++', repo: 'facebook/folly' },
  { language: 'JS', repo: 'react-bootstrap/react-bootstap' },
  { language: 'JS', repo: 'keystonejs/keystone' },
  { language: 'Obj-C', repo: 'CoderMJLee/MJRefresh' },
  { language: 'C++, Java', repo: 'facebook/rocksdb' },
  { language: 'C++, JS, Lua', repo: 'cocos2d/cocos2d-x' },
  { language: 'Python', repo: 'pandas-dev/pandas' },
  { language: 'Obj-C, C', repo: 'Mantle/Mantle' },
  { language: 'Java', repo: 'jfeinstein10/SlidingMenu' },
  { language: 'C#', repo: 'CodeHubApp/CodeHub' },
  { language: 'Resource, JS, React', repo: 'markerikson/react-redux-links' },
  { language: 'JS', repo: 'strongloop/loopback' },
  { language: 'JS', repo: 'swagger-api/swagger-ui' },
  { language: 'Resource, Streams', repo: 'substack/stream-handbook' },
  { language: 'JS', repo: 'isagalaev/highlight.js' },
  { language: 'CSS, JS', repo: 'framework7io/framework7' },
  { language: 'Resource, JS', repo: 'loverajoel/jstips' },
  { language: 'Kotlin, Java', repo: 'alibaba/p3c' },
  { language: 'Scala', repo: 'scala/scala' },
  { language: 'Java', repo: 'google/ExoPlayer' },
  { language: 'Resource, JS', repo: 'fbsamples/f8app' },
  { language: 'JS', repo: 'airbnb/lottie-web' },
  { language: 'Resource', repo: 'wearehive/project-guidelines' },
  { language: 'Go', repo: 'cayleygraph/cayley' },
  { language: 'CSS, HTML, JS', repo: 'uikit/uikit' },
  { language: 'JS', repo: 'ampproject/amphtml' },
  { language: 'Resource, CS', repo: 'Developer-Y/cs-video-courses' },
  { language: 'Shell', repo: 'tj/git-extras' },
  { language: 'JS, CSS', repo: 'ant-design/ant-design-pro' },
  { language: 'JS, CSS', repo: 'amazeui/amazeui' },
  { language: 'TS, JS', repo: 'reduxjs/reselect' },
  {
    language: 'Resource, React',
    repo: 'erikras/react-redux-universal-hot-example'
  },
  { language: 'JS, TS', repo: 'rollup/rollup' },
  { language: 'Swift', repo: 'HeroTransitions/Hero' },
  { language: 'TS, HTML', repo: 'prismagraphql/chromeless' },
  { language: 'JS, CSS, HTML', repo: 'philipwalton/solved-by-flexbox' },
  { language: 'Vim Script', repo: 'amix/vimrc' },
  { language: 'PHP', repo: 'laravel/framework' },
  { language: 'Resource, Shell', repo: 'alebcay/awesome-shell' },
  { language: 'Elixir, JS', repo: 'phoenixframework/phoenix' },
  { language: 'Go, JS, HTML', repo: 'nsqio/nsq' },
  { language: 'JS', repo: 'yaronn/blessed-contrib' },
  { language: 'JS', repo: 'feathericons/feather' },
  { language: 'Ruby, JS', repo: 'tootsuite/mastodon' },
  { language: 'JS', repo: 'selectize/selectize.js' },
  { language: 'JS', repo: 'marcuswestin/store.js' },
  { language: 'Resource, Node, JS', repo: 'alsotang/node-lessons' },
  { language: 'Obj-C', repo: 'RestKit/RestKit' },
  { language: 'C++, JS, C#, Java', repo: 'facebook/yoga' },
  { language: 'JS', repo: 'mysqljs/mysql' },
  { language: 'Obj-C', repo: 'SVProgressHUD/SVProgressHUD' },
  { language: 'JS', repo: 'chenglou/react-motion' },
  { language: 'JS', repo: 'uxsolutions/bootstrap-datepicker' },
  { language: 'JS', repo: 'VerbalExpressions/JSVerbalExpressions' },
  { language: 'Swift', repo: 'Carthage/Carthage' },
  { language: 'JS', repo: 'Shopify/draggable' },
  { language: 'Obj-C, C', repo: 'bang590/JSPatch' },
  { language: 'Go, Ruby, Shell', repo: 'junegunn/fzf' },
  {
    language: 'Resource, Python, Data Science',
    repo: 'donnemartin/data-science-ipython-notebooks'
  },
  { language: 'Python, HTML, JS, Shell', repo: 'tldr-pages/tldr' },
  { language: 'JS', repo: 'aurelia/framework' },
  { language: 'JS, CSS', repo: 'buunguyen/octotree' },
  { language: 'Java', repo: 'lgvalle/Material-Animations' },
  { language: 'JS, Vue', repo: 'benweet/stackedit' },
  { language: 'JS', repo: 'Bilibili/flv.js' },
  { language: 'Rust, Python', repo: 'servo/servo' },
  { language: 'JS', repo: 'jwagner/smartcrop.js' },
  { language: 'JS', repo: 'localForage/localForage' },
  { language: 'Resource', repo: 'phanan/htaccess' },
  { language: 'Java', repo: 'Tencent/tinker' },
  { language: 'Python, OpenEdge ABL', repo: 'fxsjy/jieba' },
  { language: 'Resource, JS', repo: 'DrkSephy/es6-cheatsheet' },
  { language: 'Java', repo: 'facebook/stetho' },
  { language: 'PHP', repo: 'composer/composer' },
  { language: 'Resource, JS', repo: 'ruanyf/jstraining' },
  { language: 'JS, TS', repo: 'styled-components/styled-components' },
  { language: 'JS, TS', repo: 'paularmstrong/normalizr' },
  { language: 'JS', repo: 'sampotts/plyr' },
  { language: 'JS, CSS', repo: 'guzzle/guzzle' },
  { language: 'Ruby', repo: 'capistrano/capistrano' },
  { language: 'Resource', repo: 'lukasz-madon/awesome-remote-job' },
  { language: 'Go', repo: 'golang/dep' },
  { language: 'JS', repo: 'gorhill/uBlock' },
  { language: 'JS', repo: 'hackiftekhar/IQKeyboardManager' },
  { language: 'Shell', repo: 'rbenv/rbenv' },
  { language: 'Clojure', repo: 'LightTable/LightTable' },
  { language: 'Java', repo: 'jenkinsci/jenkins' },
  { language: 'Ruby', repo: 'CocoaPods/CocoaPods' },
  { language: 'Resource, Webpack', repo: 'petehunt/webpack-howto' },
  { language: 'C++, C#, Dart, PHP, Java, Python', repo: 'google/flatbuffers' },
  { language: 'JS', repo: 'Automattic/wp-calypso' },
  { language: 'Resource, CSS', repo: 'AllThingsSmitty/css-protips' },
  { language: 'Go, JS', repo: 'hashicorp/vault' },
  { language: 'Resource, IOS', repo: 'cjwirth/awesome-ios-ui' },
  { language: 'Python', repo: 'google/python-fire' },
  { language: 'Vim Script', repo: 'vim-airline/vim-airline' },
  { language: 'Scala, Java', repo: 'playframework/playframework' },
  {
    language: 'Resource, JS, React',
    repo: 'brillout/awesome-react-components'
  },
  { language: 'HTML', repo: 'Microsoft/dotnet' },
  { language: 'Jave', repo: 'androidannotations/androidannotations' },
  { language: 'Python', repo: 'binux/pyspider' },
  { language: 'HTML', repo: 'keen/dashboards' },
  {
    language: 'Resource, React native',
    repo: 'reactnativecn/react-native-guide'
  },
  { language: 'Java, Kotlin, HTML', repo: 'nickbutcher/plaid' },
  { language: 'Java, JS, Obj-C, C++', repo: 'apache/incubator-weex' },
  { language: 'JS', repo: 'vuejs/vue-router' },
  { language: 'JS, TS', repo: 'redux-saga/redux-saga' },
  { language: 'JS', repo: 'shadowsocks/ShadowsocksX-NG' },
  { language: 'JS', repo: 'containous/traefik' },
  { language: 'Swift, Obj-C', repo: 'parkjs814/AlgorithmVisualizer' },
  { language: 'C', repo: 'stedolan/jq' },
  { language: 'Ruby', repo: 'sinatra/sinatra' },
  {
    language: 'Resource, Android',
    repo: 'android10/Android-CleanArchitecture'
  },
  { language: 'Haskell', repo: 'PostgREST/postgrest' },
  { language: 'JS', repo: 'CymChad/BaseRecyclerViewAdapterHelper' },
  { language: 'Java', repo: 'rapid7/metasploit-framework' },
  { language: 'Resource, Chinese', repo: 'hzlzh/Best-App' },
  { language: 'Swift', repo: 'onevcat/Kingfisher' },
  { language: 'PHP', repo: 'PHPMailer/PHPMailer' },
  { language: 'JS, Java, Obj-c, C++', repo: 'ptmt/react-native-macos' },
  { language: 'C++, C', repo: 'Tencent/mars' },
  { language: 'Go', repo: 'pingcap/tidb' },
  { language: 'Obj-C', repo: 'CocoaLumberjack/CocoaLumberjack' },
  { language: 'Shell, Python', repo: 'source-foundry/Hack' },
  { language: 'Haskell', repo: 'jgm/pandoc' },
  { language: 'Vim Script', repo: 'tpope/vim-pathogen' },
  { language: 'Python', repo: 'sqlmapproject/sqlmap' },
  { language: 'Resource, PHP', repo: 'php-fig/fig-standards' },
  { language: 'JS', repo: 'pouchdb/pouchdb' },
  { language: 'Python, JS', repo: 'HelloZeroNet/ZeroNet' },
  { language: 'JS, HTML', repo: 'thomaspark/bootswatch' },
  { language: 'Matlab, Lua, Cuda', repo: 'luanfujun/deep-photo-styletransfer' },
  { language: 'Resource, React, JS', repo: 'petehunt/react-howto' },
  {
    language: 'Resource, Functional Programming',
    repo: 'hemanth/functional-programming-jargon'
  },
  { language: 'Resource, REST API', repo: 'abhishekbanthia/Public-APIs' },
  { language: 'JS', repo: 'ramda/ramda' },
  { language: 'JS', repo: 'DmitryBaranovskiy/raphael' },
  { language: 'JS', repo: 'Microsoft/monaco-editor' },
  { language: 'Lua, HTML', repo: 'nagadomi/waifu2x' },
  { language: 'Vue, JS, CSS', repo: 'airyland/vux' },
  { language: 'Resource, Redux', repo: 'xgrommx/awesome-redux' },
  { language: 'Resource, Deep Learning, Chinese', repo: 'ty4z2008/Qix' },
  { language: 'Resource, Swift', repo: 'allenwong/30DaysofSwift' },
  { language: 'Shell, PowerShell', repo: 'powerline/fonts' },
  { language: 'C++', repo: 'godotengine/godot' },
  { language: 'Java', repo: 'realm/realm-java' },
  { language: 'JS, HTML', repo: 'niklasvh/html2canvas' },
  { language: 'Resource, Interviews', repo: 'keon/algorithms' },
  { language: 'JS, HTML, TS', repo: 'BrowserSync/browser-sync' },
  { language: 'HTML', repo: 'google/WebFundamentals' },
  { language: 'Julia, C, C++', repo: 'JuliaLang/julia' },
  { language: 'Obj-C', repo: 'robbiehanson/CocoaAsyncSocket' },
  { language: 'Resource, Chinese', repo: 'xitu/gold-miner' },
  { language: 'Go, Python', repo: 'google/grumpy' },
  { language: 'JS', repo: 'maxwellito/vivus' },
  { language: 'Resource, JS', repo: 'denysdovhan/wtfjs' },
  { language: 'Resource', repo: 'grab/front-end-guide' },
  { language: 'Kotlin', repo: 'googlesamples/android-UniversalMusicPlayer' },
  { language: 'Python', repo: 'fabric/fabric' },
  { language: 'Resource, Security', repo: 'shieldfy/API-Security-Checklist' },
  { language: 'Crystal', repo: 'crystal-lang/crystal' },
  { language: 'JS', repo: 'karma-runner/karma' },
  { language: 'C#, C++', repo: 'dotnet/coreclr' },
  { language: 'Java', repo: 'pockethub/PocketHub' },
  { language: 'JS', repo: 'Netflix/falcor' },
  { language: 'JS', repo: 'goldfire/howler.js' },
  { language: 'Ruby', repo: 'thoughtbot/paperclip' },
  { language: 'JS', repo: 'MrRio/jsPDF' },
  { language: 'Python', repo: 'tensorflow/magenta' },
  { language: 'C#, Visual Basic', repo: 'dotnet/roslyn' },
  { language: 'JS', repo: 'elastic/kibana' },
  { language: 'Obj-C', repo: 'Flipboard/FLEX' },
  {
    language: 'Resource, Learning',
    repo: 'bmorelli25/Become-A-Full-Stack-Web-Developer'
  },
  { language: 'Obj-C', repo: 'kevinzhow/PNChart' },
  { language: 'PHP', repo: 'phacility/phabricator' },
  { language: 'TS', repo: 'AngularClass/angular-starter' },
  { language: 'Swift', repo: 'realm/SwiftLint' },
  {
    language: 'Resource, Android, Chinese',
    repo: 'kesenhoo/android-training-course-in-chinese'
  },
  {
    language: 'Resource, Learning',
    repo: 'dexteryy/spellbook-of-modern-webdev'
  },
  { language: 'TS', repo: 'pedronauck/docz' },
  { language: 'Go', repo: 'revel/revel' },
  { language: 'JS', repo: 'tj/commander.js' },
  { language: 'Resource, Node, Chinese', repo: 'nswbmw/N-blog' },
  { language: 'Haskell', repo: 'koalaman/shellcheck' },
  { language: 'Vue, CSS, JS', repo: 'iview/iview' },
  { language: 'Shell', repo: 'facebook/graphql' },
  { language: 'Ruby', repo: 'spree/spree' },
  { language: 'Resource, Swift', repo: 'apple/swift-evolution' },
  { language: 'Swift', repo: 'Ramotion/animated-tab-bar' },
  { language: 'PHP, JS, HTML', repo: 'roots/sage' },
  { language: 'C++, Scala, R, Python, Cuda, Java', repo: 'dmlc/xgboost' },
  { language: 'Ruby, Java', repo: 'elastic/logstash' },
  { language: 'Python', repo: 'spotify/luigi' },
  { language: 'JS', repo: 'fabricjs/fabric.js' },
  { language: 'OCaml, Java, C++', repo: 'facebook/infer' },
  { language: 'Vim Script', repo: 'tpope/vim-fugitive' },
  { language: 'C++, Python', repo: 'google/googletest' },
  { language: 'Python, Java', repo: 'localstack/localstack' },
  { language: 'Resource, TensorFlow', repo: 'jtoy/awesome-tensorflow' },
  { language: 'Python', repo: 'encode/django-rest-framework' },
  { language: 'Java', repo: 'greenrobot/greenDAO' },
  { language: 'JS', repo: 'handsontable/handsontable' },
  { language: 'JS', repo: 'systemjs/systemjs' },
  { language: 'JS', repo: 'eslint/eslint' },
  { language: 'Java, Scala', repo: 'apache/kafka' },
  { language: 'Resource', repo: 'gothinkster/realworld' },
  { language: 'Ruby', repo: 'thoughtbot/bourbon' },
  { language: 'Resource, Swift', repo: 'ochococo/Design-Patterns-In-Swift' },
  { language: 'Python', repo: 'sshuttle/sshuttle' },
  { language: 'JS', repo: 'chriso/validator.js' },
  { language: 'Go, MakeFile', repo: 'joewalnes/websocketd' },
  { language: 'Vim Script', repo: 'scrooloose/nerdtree' },
  { language: 'HTML, JS', repo: 'metafizzy/isotope' },
  { language: 'CoffeeScript', repo: 'basecamp/trix' },
  { language: 'Swift', repo: 'fullstackio/FlappySwift' },
  { language: 'TS', repo: 'flatpickr/flatpickr' },
  { language: 'JS, CSS', repo: 'stylus/stylus' },
  { language: 'Swift', repo: 'CosmicMind/Material' },
  { language: 'Obj-C', repo: 'slackhq/SlackTextViewController' },
  { language: 'JS', repo: 'knockout/knockout' },
  { language: 'Vim Script', repo: 'junegunn/vim-plug' },
  { language: 'JS', repo: 'docker/kitematic' },
  { language: 'Resource, Design', repo: 'gztchan/awesome-design' },
  { language: 'Vim Script', repo: 'vim-syntastic/syntastic' },
  { language: 'Go', repo: 'ipfs/go-ipfs' },
  { language: 'Python', repo: 'Rochester-NRT/RocAlphaGo' },
  { language: 'JS', repo: 'NodeRedis/node_redis' },
  { language: 'Python', repo: 'mitmproxy/mitmproxy' },
  { language: 'PHP, Zephyr', repo: 'phalcon/cphalcon' },
  { language: 'Java, JS, Obj-C', repo: 'react-community/lottie-react-native' },
  { language: 'PHP', repo: 'slimphp/Slim' },
  { language: 'JS', repo: 'JedWatson/react-select' },
  { language: 'Python, JS', repo: 'apache/incubator-airflow' },
  { language: 'JS', repo: 'nodemailer/nodemailer' },
  { language: 'Java', repo: 'alibaba/vlayout' },
  { language: 'JS', repo: 'winstonjs/winston' },
  { language: 'Shell, Roff', repo: 'pyenv/pyenv' },
  { language: 'Resource, JS', repo: 'shichuan/javascript-patterns' },
  { language: 'JS', repo: 'hapijs/hapi' },
  { language: 'JS, HTML, Roff', repo: 'jsdom/jsdom' },
  { language: 'C', repo: 'irungentoo/toxcore' },
  { language: 'JS', repo: 'paperjs/paper.js' },
  { language: 'Go, JS', repo: 'minio/minio' },
  { language: 'Swift, Ob-C', repo: 'mxcl/PromiseKit' },
  { language: 'Resource, API', repo: 'Microsoft/api-guidelines' },
  { language: 'CSS, PHP', repo: 'Automattic/_s' },
  { language: 'Java', repo: 'signalapp/Signal-Android' },
  { language: 'Go', repo: 'labstack/echo' },
  { language: 'C, Assembly', repo: 'FFmpeg/FFmpeg' },
  { language: 'Obj-C', repo: 'matryer/bitbar' },
  { language: 'Ruby', repo: 'ruby-grape/grape' },
  { language: 'Java', repo: 'mikepenz/MaterialDrawer' },
  { language: 'JS, HTML', repo: 'geeeeeeeeek/electronic-wechat' },
  { language: 'Go, Shell', repo: 'kubernetes/minikube' },
  { language: 'PHP', repo: 'phanan/koel' },
  { language: 'JS', repo: 'sindresorhus/pageres' },
  { language: 'Shell, C++', repo: 'fish-shell/fish-shell' },
  { language: 'Python', repo: 'saltstack/salt' },
  { language: 'JS', repo: 'guillaumepotier/Parsley.js' },
  { language: 'Python', repo: 'home-assistant/home-assistant' },
  { language: 'C#', repo: 'StackExchange/Dapper' },
  { language: 'C++, TS, JS', repo: 'Microsoft/napajs' },
  { language: 'JS', repo: 'rwaldron/johnny-five' },
  { language: 'JS', repo: 'jquery-validation/jquery-validation' },
  { language: 'JS, Vue', repo: 'vuejs/vue-devtools' },
  { language: 'Ruby', repo: 'rubocop-hq/rubocop' },
  { language: 'JS', repo: 'ccampbell/mousetrap' },
  { language: 'Java, C, C++', repo: 'DrKLO/Telegram' },
  { language: 'Ruby, Shell', repo: 'jordansissel/fpm' },
  { language: 'Ruby', repo: 'teamcapybara/capybara' },
  { language: 'Shell', repo: 'sorin-ionescu/prezto' },
  { language: 'Python, JS', repo: 'nicolargo/glances' },
  { language: 'JS', repo: 'arasatasaygin/is.js' },
  { language: 'Resource, Bash', repo: 'Idnan/bash-guide' },
  { language: 'Python, Shell', repo: 'powerline/powerline' },
  { language: 'Lua, Python', repo: 'cmusatyalab/openface' },
  { language: 'JS, Java, TS, HTML', repo: 'jhipster/generator-jhipster' },
  { language: 'Ruby', repo: 'resque/resque' },
  { language: 'Resource, Docker', repo: 'veggiemonk/awesome-docker' },
  { language: 'Java', repo: 'hdodenhof/CircleImageView' },
  { language: 'Obj-C', repo: 'OpenEmu/OpenEmu' },
  { language: 'Resource, Front-end', repo: 'moklick/frontend-stuff' },
  { language: 'Resource, JS', repo: 'ruanyf/es6tutorial' },
  { language: 'C++, C', repo: 'ocornut/imgui' },
  { language: 'JS', repo: 'MithrilJS/mithril.js' },
  { language: 'PHP, JS, HTML', repo: 'matomo-org/matomo' },
  { language: 'Resource, Ethereum', repo: 'ethereum/wiki' },
  { language: 'Go', repo: 'hashicorp/packer' },
  { language: 'Go', repo: 'jinzhu/gorm' },
  { language: 'Resource, Java', repo: 'winterbe/java8-tutorial' },
  { language: 'JS', repo: 'EnterpriseQualityCoding/FizzBuzzEnterpriseEdition' },
  { language: 'JS, CSS', repo: 'HubSpot/tether' },
  { language: 'JS', repo: 'typicode/lowdb' },
  { language: 'JS', repo: 'harthur/brain' },
  { language: 'Obj-C', repo: 'facebook/SocketRocket' },
  { language: 'Ruby', repo: 'mperham/sidekiq' },
  { language: 'JS, CSS', repo: 'facebook/Docusaurus' },
  { language: 'JS', repo: 'gorHill/uBlock' },
  { language: 'Go, JS', repo: 'buger/goreplay' },
  { language: 'JS', repo: 'Khan/KaTeX' },
  { language: 'Resource, WebAssembly', repo: 'WebAssembly/design' },
  { language: 'JS', repo: 'svg/svgo' },
  { language: 'Resource, Data Science', repo: 'datasciencemasters/go' },
  { language: 'CSS', repo: 'ConnorAtherton/loaders.css' },
  { language: 'C++, C', repo: 'apple/foundationdb' },
  { language: 'C#, PowerShell', repo: 'PowerShell/PowerShell' },
  { language: 'JS, Python', repo: 'facebook/nuclide' },
  { language: 'C++', repo: 'uNetworking/uWebSockets' },
  { language: 'JS', repo: 'qrohlf/trianglify' },
  { language: 'JS', repo: 'graphql/graphql-js' },
  { language: 'Resource, Mac OS', repo: 'nikitavoloboev/my-mac-os' },
  { language: 'Go', repo: 'google/cadvisor' },
  { language: 'Ruby', repo: 'carrierwaveuploader/carrierwave' },
  { language: 'JS', repo: 'nodejitsu/node-http-proxy' },
  { language: 'Swift', repo: 'lhc70000/iina' },
  { language: 'Clojure', repo: 'clojure/clojurescript' },
  { language: 'JS', repo: 'purifycss/purifycss' },
  { language: 'C, Roff', repo: 'tmux/tmux' },
  { language: 'JS, Smarty', repo: 'NodeBB/NodeBB' },
  { language: 'Resource, Swift', repo: 'raywenderlich/swift-style-guide' },
  { language: 'Go', repo: 'go-kit/kit' },
  { language: 'Java, JS, C#, C++, HTML', repo: 'SeleniumHQ/selenium' },
  { language: 'C, Shell', repo: 'twitter/twemproxy' },
  { language: 'Resource, Ruby', repo: 'markets/awesome-ruby' },
  { language: 'Scala, Java', repo: 'akka/akka' },
  { language: 'Resource', repo: 'learn-anything/maps' },
  { language: 'Python', repo: 'celery/celery' },
  { language: 'TS, CSS, HTML', repo: 'akveo/ngx-admin' },
  { language: 'Go, Lua', repo: 'zyedidia/micro' },
  { language: 'Resource, Chinese', repo: 'TeamStuQ/skill-map' },
  { language: 'CSS, HTML', repo: 'mrmrs/colors' },
  { language: 'Go', repo: 'kataras/iris' },
  { language: 'Ruby', repo: 'activeadmin/activeadmin' },
  { language: 'Shell, MakeFile, Dockerfile', repo: 'redox-os/redox' },
  { language: 'Shell', repo: 'tj/n' },
  { language: 'PHP', repo: 'getgrav/grav' },
  { language: 'JS', repo: 'zeit/pkg' },
  { language: 'Python', repo: 'google/yapf' },
  { language: 'JS', repo: 'jacomyal/sigma.js' },
  { language: 'JS', repo: 'typicode/husky' },
  { language: 'CSS, HTML', repo: 'chinchang/hint.css' },
  { language: 'JS, TS', repo: 'typicode/hotel' },
  { language: 'C', repo: 'facebook/zstd' },
  { language: 'JS, CSS, Chinese', repo: 'sentsin/layui' },
  { language: 'JS', repo: 'erikras/redux-form' },
  { language: 'JS', repo: 'senchalabs/connect' },
  { language: 'Swift', repo: 'mozilla-mobile/firefox-ios' },
  { language: 'JS, HTML', repo: 'twitter/twemoji' },
  { language: 'Swift, Obj-C', repo: 'Ramotion/folding-cell' },
  { language: 'Java', repo: 'eclipse/vert.x' },
  { language: 'C#', repo: 'mxgmn/WaveFunctionCollapse' },
  { language: 'JS', repo: 'jshint/jshint' },
  { language: 'Resource, Linux', repo: 'LewisVo/Awesome-Linux-Software' },
  { language: 'TS', repo: 'cyclejs/cyclejs' },
  { language: 'Python, JS, Java', repo: 'odoo/odoo' },
  { language: 'JS', repo: 'gaearon/react-hot-loader' },
  { language: 'CoffeeScript, HTML', repo: 'philc/vimium' },
  { language: 'Java, Kotlin', repo: 'orhanobut/logger' },
  { language: 'Go', repo: 'rkt/rkt' },
  { language: 'JS', repo: 'feathersjs/feathers' },
  { language: 'JS', repo: 'nosir/cleave.js' },
  { language: 'C++', repo: 'CRYTEK/CRYENGINE' },
  { language: 'Java', repo: 'apache/hadoop' },
  { language: 'Python, JS, HTML, CSS', repo: 'getredash/redash' },
  { language: 'JS', repo: 'spencermountain/compromise' },
  { language: 'JS', repo: 'facebook/react-devtools' },
  { language: 'C', repo: 'libuv/libuv' },
  { language: 'Resource, API', repo: 'OAI/OpenAPI-Specification' },
  { language: 'Shell, Groovy, BatchFile', repo: 'babun/babun' },
  { language: 'PHP', repo: 'cakephp/cakephp' },
  { language: 'C', repo: 'torch/torch7' },
  { language: 'JS', repo: 'coryhouse/react-slingshot' },
  { language: 'Ruby', repo: 'javan/whenever' },
  { language: 'Python', repo: 'getpelican/pelican' },
  { language: 'JS', repo: 'SheetJS/js-xlsx' },
  { language: 'CoffeeScript, HTML', repo: 'FelisCatus/SwitchyOmega' },
  { language: 'Ruby, HTML, CSS', repo: 'atech/postal' },
  { language: 'Resource, AI', repo: 'kailashahirwar/cheatsheets-ai' },
  { language: 'JS', repo: 'FredrikNoren/ungit' },
  { language: 'Obj-C', repo: 'CoderMJLee/MJExtension' },
  { language: 'JS', repo: 'CodeSeven/toastr' },
  { language: 'C, Perl', repo: 'alibaba/tengine' },
  { language: 'PHP', repo: 'serbanghita/Mobile-Detect' },
  { language: 'JS', repo: 'mishoo/UglifyJS2' },
  { language: 'JS', repo: 'FineUploader/fine-uploader' },
  { language: 'Java', repo: 'google/agera' },
  { language: 'JS', repo: 'restify/node-restify' },
  { language: 'JS', repo: 'marionettejs/backbone.marionette' },
  { language: 'Java, Clojure', repo: 'clojure/clojure' },
  { language: 'Shell, Roff', repo: 'rupa/z' },
  { language: 'Resource, IOS', repo: 'Aufree/trip-to-iOS' },
  { language: 'Resource, VIM', repo: 'mhinz/vim-galore' },
  { language: 'PHP, ASP, Shell, Perl', repo: 'danielmiessler/SecLists' },
  { language: 'C, C++', repo: 'obsproject/obs-studio' },
  { language: 'C, C++, Java, Python', repo: 'arduino/Arduino' },
  { language: 'Java, C++', repo: 'deeplearning4j/deeplearning4j' },
  { language: 'Vim Script, Go', repo: 'fatih/vim-go' },
  {
    language: 'Resource, Machine Learning',
    repo: 'hangtwenty/dive-into-machine-learning'
  },
  { language: 'JS', repo: 'c3js/c3' },
  { language: 'C++, Python, Cuda, C', repo: 'pytorch/pytorch' },
  {
    language: 'Resource, Python, Machine Learning',
    repo: 'rasbt/python-machine-learning-book'
  },
  { language: 'JS', repo: 'nightwatchjs/nightwatch' },
  { language: 'JS, CoffeeScript, CSS', repo: 'Automattic/kue' },
  { language: 'JS, C++', repo: 'Microsoft/ChakraCore' },
  { language: 'Python, JS, HTML, CSS', repo: 'mailpile/Mailpile' }
];

const creationParams = {
  AttributeDefinitions: [
    {
      AttributeName: 'ID',
      AttributeType: 'N'
    },
    {
      AttributeName: 'Repo',
      AttributeType: 'S'
    }
  ],
  KeySchema: [
    {
      AttributeName: 'ID',
      KeyType: 'HASH'
    },
    {
      AttributeName: 'Repo',
      KeyType: 'RANGE'
    }
  ],
  ProvisionedThroughput: {
    ReadCapacityUnits: 1,
    WriteCapacityUnits: 5
  },
  TableName: 'Repo_Issues'
};

const deletionParams = {
  TableName: 'Repo_Issues'
};

const paramsWaitFor = {
  TableName: 'Repo_Issues'
};

const batchParams = {
  RequestItems: {
    Repo_Issues: null
  }
};

const scanParams = {
  TableName: 'Repo_Issues'
};

module.exports = {
  githubOptions,
  repos,
  creationParams,
  deletionParams,
  paramsWaitFor,
  batchParams,
  scanParams
};
